#!/bin/bash

#Make Deployment Properties Configuration File
mkdir -p /Library/Application\ Support/CrashPlan
echo "DEPLOYMENT_URL=clients.us2.code42.com
DEPLOYMENT_POLICY_TOKEN=defe15bf-d455-455a-8bb1-07fc8036e8f1
CP_SILENT=true
DEVICE_CLOAKED=false" > /Library/Application\ Support/CrashPlan/deploy.properties

# Path to where the installers live
cd /private/var/tmp/code42

# Determine if device is Intel or Apple Silicon
arch=$(/usr/bin/arch)
if [ "$arch" == "arm64" ]; then
sudo hdiutil attach Code42_8.8.2_1525200006882_143_Mac-arm64.dmg
sudo installer -package /Volumes/Code42/Install\ Code42.pkg -target /

# Let things settle down
sleep 1
hdiutil detach /Volumes/Code42

elif [ "$arch" == "i386" ]; then

sudo hdiutil attach Code42_8.8.2_1525200006882_143_Mac-x86-64.dmg
sudo installer -package /Volumes/Code42/Install\ Code42.pkg -target /

# Let things settle down
sleep 1
hdiutil detach /Volumes/Code42

fi
