#!/bin/bash
assimilate_ownership() {
  echo "=> Assimilate ownership on '/Applications/Dialpad.app'"
  chown -R $(scutil <<< "show State:/Users/ConsoleUser" | awk -F': ' '/[[:space:]]+Name[[:space:]]:/ { if ( $2 != "loginwindow" ) { print $2 }}'):staff "/Applications/Dialpad.app"
}

fi
