#!/bin/sh


#URL Download
DOWNLOAD_URL="https://storage.googleapis.com/dialpad_native/osx/Dialpad.dmg"

#Kill Running Application
pkill Dialpad*

# Create a temporary directory in which to mount the .dmg
tmp_mount=`/usr/bin/mktemp -d /tmp/Dialpad.XXXX`

# Attach the install DMG directly from Mozilla's servers (ensuring HTTPS)
hdiutil attach "$( eval echo "${DOWNLOAD_URL}" )" -nobrowse -quiet -mountpoint "${tmp_mount}"

rm -dfR "/Applications/Dialpad.app"

ditto "${tmp_mount}/Dialpad.app" "/Applications/Dialpad.app"

# Let things settle down
sleep 1

# Detach the dmg and remove the temporary mountpoint
hdiutil detach "${tmp_mount}" && /bin/rm -rf "${tmp_mount}"

if [ -e "/Applications/Dialpad.app" ]; then
    echo "******Latest version of Dialpad is installed on target Mac.******"
fi
  
# Open App For User
open -a "/Applications/Dialpad.app"

exit 0;
