#!/bin/bash
# Disable Remote Management - ARD
#Approved by wkuang, jfrantz, lamador
#6-26-2020

/System/Library/CoreServices/RemoteManagement/ARDAgent.app/Contents/Resources/kickstart -deactivate

exit 0
