#!/bin/bash

# Identify the name of the app
APP_NAME="Dialpad.app"

#Kill Running Application
pkill Dialpad*

# Identify the path to where the package places the app
INSTALLED_APP_PATH="/Applications/$APP_NAME"

# Find the logged in username
loggedInUser=$(/usr/bin/python -c 'from SystemConfiguration import SCDynamicStoreCopyConsoleUser; import sys; username = (SCDynamicStoreCopyConsoleUser(None, None, None) or [None])[0]; username = [username,""][username in [u"loginwindow", None, u""]]; sys.stdout.write(username + "\n");')

# Move the app from the Applications directory to the user's Application directory
/bin/mv "$INSTALLED_APP_PATH" "/Users/$loggedInUser/Applications"


#assimilate ownership
chown -R $(scutil <<< "show State:/Users/ConsoleUser" | awk -F': ' '/[[:space:]]+Name[[:space:]]:/ { if ( $2 != "loginwindow" ) { print $2 }}'):staff "/Users/$loggedInUser/Applications/Dialpad.app"

#open the app for the user
open -a Dialpad "/Users/$loggedInUser/Applications"

exit 0
