#!/bin/bash

export TERM=xterm-256color

mkdir /private/var/tmp/r7agent

cd /private/var/tmp/r7agent

sudo /usr/bin/curl -O https://s3.amazonaws.com/com.rapid7.razor.public/endpoint/agent/latest/darwin/x86_64/agent_control_latest_x64.sh

sudo chmod u+x /private/var/tmp/r7agent/agent_installer-arm64.sh

sudo /bin/sh /private/var/tmp/r7agent/agent_installer-arm64.sh install_start --token us:5082b6b7-78ba-4945-997d-3ccd0fb5cc93

exit 0
