#!/bin/bash
##UPDATE dmgName FOR NEW VERSIONS OF ANYCONNECT##
ciscoDir="/opt/cisco"
## DMG Image name provided in script parameter 4
## Installer Volume name in parameter 5
## XML File name in parameter 6
## OrgInfo name in paramater 7
dmgName=$4 
waitRoom="/Library/Application Support/JAMF/Waiting Room"
echo "


"
echo "###########################"
if [[ -d $ciscoDir/anyconnect/bin ]]; 
then
    echo "Anyconnect Directory found"
    echo "Found umbrella plugin...calling uninstall script"
    sudo "$ciscoDir/anyconnect/bin/umbrella_uninstall.sh"
    echo "Script complete"
else
    echo "no remnants of the anyconnect directory found"
fi
echo "#############################"

echo "#############################"
echo "Status check: Prep Complete"
echo "#############################"

echo "########################################"
echo "Beginning the installation"
echo "attempting to mount dmg"
/usr/bin/hdiutil attach "$waitRoom"/"$dmgName" -nobrowse
echo "DMG mounted. About to call installer..."
echo "########################################"
installer -pkg "/Volumes/$5/AnyConnect.pkg" -applyChoiceChangesXML "/Volumes/$5/$6" -target /
echo "Package installed"
echo "#############################"
cp -R "/Volumes/$5/$7" "/opt/cisco/anyconnect/umbrella"
echo "Moved OrgInfo.json"
echo "#############################"
/usr/bin/hdiutil detach "/Volumes/$5"
echo "######################################"
echo "AnyConnect 4.10 installation is complete"
echo "######################################"
exit 0
